// RU translations for Airbnb room names + amenities (finite vocabulary).
export const ROOM_RU: Record<string, string> = {
  'Living room': 'Гостиная',
  'Full kitchen': 'Кухня',
  'Kitchen': 'Кухня',
  'Dining area': 'Столовая зона',
  'Bedroom': 'Спальня',
  'Bedroom 1': 'Спальня 1',
  'Bedroom 2': 'Спальня 2',
  'Full bathroom': 'Ванная',
  'Bathroom': 'Ванная',
  'Balcony': 'Балкон',
  'Patio': 'Патио',
  'Backyard': 'Двор',
  'Exterior': 'Снаружи',
  'Laundry area': 'Прачечная',
  'Workspace': 'Рабочее место',
  'Gym': 'Спортзал',
  'Pool': 'Бассейн',
};

export const AMENITY_RU: Record<string, string> = {
  'Air conditioning': 'Кондиционер',
  'Backyard': 'Двор',
  'Beach access': 'Выход к пляжу',
  'Beach essentials': 'Пляжные принадлежности',
  'Bed linens': 'Постельное бельё',
  'Body soap': 'Гель для душа',
  'Cleaning products': 'Чистящие средства',
  'Clothing storage': 'Место для одежды',
  'Coffee': 'Кофе',
  'Coffee maker': 'Кофеварка',
  'Cooking basics': 'Набор для готовки',
  'Crib': 'Детская кроватка',
  'Dedicated workspace': 'Рабочее место',
  'Dining table': 'Обеденный стол',
  'Dishes and silverware': 'Посуда и приборы',
  'Dishwasher': 'Посудомойка',
  'Double bed': 'Двуспальная кровать',
  'Dryer': 'Сушильная машина',
  'Drying rack for clothing': 'Сушилка для белья',
  'Elevator': 'Лифт',
  'Essentials': 'Базовые принадлежности',
  'Extra pillows and blankets': 'Доп. подушки и одеяла',
  'Free parking on premises': 'Бесплатная парковка',
  'Freezer': 'Морозилка',
  'Hair dryer': 'Фен',
  'Hangers': 'Вешалки',
  'Heating': 'Отопление',
  'Hot water': 'Горячая вода',
  'Hot water kettle': 'Электрочайник',
  'Iron': 'Утюг',
  'King bed': 'Кровать king-size',
  'Kitchen': 'Кухня',
  'Microwave': 'Микроволновка',
  'Mini fridge': 'Мини-холодильник',
  'Outdoor dining area': 'Уличная обеденная зона',
  'Outdoor furniture': 'Уличная мебель',
  'Patio or balcony': 'Патио или балкон',
  'Private entrance': 'Отдельный вход',
  'Queen bed': 'Кровать queen-size',
  'Refrigerator': 'Холодильник',
  'Resort access': 'Доступ к инфраструктуре',
  'Room-darkening shades': 'Плотные шторы',
  'Shampoo': 'Шампунь',
  'Sofa bed': 'Диван-кровать',
  'Stove': 'Плита',
  'TV': 'ТВ',
  'Toaster': 'Тостер',
  'Washer': 'Стиральная машина',
  'Waterfront': 'У воды',
  'Wifi': 'Wi-Fi',
  'Wine glasses': 'Винные бокалы',
};

export const tRoom = (s: string) => ROOM_RU[s] || s;
export const tAmenity = (s: string) => AMENITY_RU[s] || s;
