-- guide_places.tags (subcategories from Tilda parts)
update guide_places set tags='["Asian dining", "Restaurants"]'::jsonb where slug='japan-33';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='milevskii-coffee';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='nova-coffee';
update guide_places set tags='["Coffee"]'::jsonb where slug='livi-coffee';
update guide_places set tags='["Dining Around Batumi"]'::jsonb where slug='elly-restaurant-gonio';
update guide_places set tags='["Dining Around Batumi"]'::jsonb where slug='botanico-cafe';
update guide_places set tags='["Gastro shops"]'::jsonb where slug='alcobrand';
update guide_places set tags='["Gastro shops"]'::jsonb where slug='gastronome-batumi';
update guide_places set tags='["Gastro shops", "Bars"]'::jsonb where slug='8000-vintages';
update guide_places set tags='["Bars", "Gastro shops"]'::jsonb where slug='garage-wines-wine-bar';
update guide_places set tags='["Bars"]'::jsonb where slug='qube-bar';
update guide_places set tags='["Bars"]'::jsonb where slug='gimlet-bar';
update guide_places set tags='["Restaurants"]'::jsonb where slug='medea-restaurant';
update guide_places set tags='["Restaurants"]'::jsonb where slug='brasserie-1900';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='moonrise';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='ravi-neobistro';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='rhino-coffee';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='minimalist-coffee-and-food';
update guide_places set tags='["Cafes"]'::jsonb where slug='nord-specialty-coffee-food';
update guide_places set tags='["Coffee"]'::jsonb where slug='nord-coffee-old-town';
update guide_places set tags='["Restaurants", "Coffee", "Cafes"]'::jsonb where slug='pure-bistro';
update guide_places set tags='["Restaurants"]'::jsonb where slug='nisha';
update guide_places set tags='["Bars"]'::jsonb where slug='1905-bar';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='kopi-brew';
update guide_places set tags='["Restaurants"]'::jsonb where slug='the-kitchen-by-rooms';
update guide_places set tags='["Restaurants"]'::jsonb where slug='daphna-batumi';
update guide_places set tags='["Restaurants"]'::jsonb where slug='ambassadori-restaurant';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='urban-coffee';
update guide_places set tags='["Restaurants"]'::jsonb where slug='panorama-restaurant';
update guide_places set tags='["Restaurants"]'::jsonb where slug='g-garden-restaurant';
update guide_places set tags='["Restaurants"]'::jsonb where slug='tiflis';
update guide_places set tags='["Coffee", "Cafes"]'::jsonb where slug='kava-lova';
update guide_places set tags='["Coffee"]'::jsonb where slug='pure-coffee';
update guide_places set tags='["Coworking"]'::jsonb where slug='d-block-workspace-rooms-batumi';
update guide_places set tags='["Coworking"]'::jsonb where slug='terminal-coworking';
update guide_places set tags='["Coworking"]'::jsonb where slug='lendspace';
update guide_places set tags='["SPA", "Bathhouses", "Massage"]'::jsonb where slug='grand-bellagio-wellness-spa';
update guide_places set tags='["SPA", "Bathhouses", "Massage", "Fitness"]'::jsonb where slug='orchid-spa-batumi';
update guide_places set tags='["SPA", "Bathhouses", "Massage"]'::jsonb where slug='eforea-spa-at-hilton-batumi';
update guide_places set tags='["SPA", "Bathhouses", "Massage", "Fitness"]'::jsonb where slug='sheraton-batumi-shine-spa';
update guide_places set tags='["SPA", "Bathhouses", "Massage", "Fitness"]'::jsonb where slug='colosseum-marina-spa';
update guide_places set tags='["SPA", "Bathhouses", "Massage", "Fitness"]'::jsonb where slug='le-m-ridien-batumi-spa-wellness';
update guide_places set tags='["SPA", "Bathhouses", "Massage", "Fitness"]'::jsonb where slug='gardenia-spa-at-steps-batumi';
update guide_places set tags='["Scooters & Bikes"]'::jsonb where slug='jet-scooter-rent';
update guide_places set tags='["Taxi Apps", "Transfers"]'::jsonb where slug='maxim-taxi';
update guide_places set tags='["Taxi Apps", "Transfers"]'::jsonb where slug='yandex-go-taxi';
update guide_places set tags='["Taxi Apps", "Transfers"]'::jsonb where slug='bolt-taxi';
update guide_places set tags='["Car Sharing"]'::jsonb where slug='getmancar-carsharing';
update guide_places set tags='["Car Rental"]'::jsonb where slug='easyrent-car-rental';
update guide_places set tags='["Car Rental"]'::jsonb where slug='vasily-car-rental';
update guide_places set tags='["Car Rental"]'::jsonb where slug='geo-drive-car-rental';